### ISSUE TITLE
Upgrade HandsonTable 0.26.1

### ISSUE THREAD

**Issue by melloware** [marklcg/jsf-sheet#3]
When upgrading to Handsontable 0.26.1 which fixes tons of IE11 performance issue and bugs we found one issue where if a column was sortable and had a filter when you click on the filter input box it would not focus it.

Somehow the TH being onClick was eating the click and it would not allow you to edit the Filter input box in IE11 or Chrome.  Our fix was to add the following and it seems to have fixed it but not sure if it is the right fix.

in sheet.js

``` javascript
        $(TH).bind('click').click(function(e) {
            $this.sortClick($this, e, col);

            // focus the filter if exists
            var filter = $(TH).find('input');
            if (filter) {
                filter.focus();
            }
        });
```

**Comment by marklcg** [comment]
So I'm not sure that is the correct fix.  That forces focus, but the focus is lost the first time due to my call to destroyEditor.  The call is made to ensure that if the user is in the middle of edits and clicks the filter to focus, that we update the data before focusing.  Somehow that call changed and it steals focus.  I can re-focus after the destroy call, but it seems to perform poorly. So looking into that.

**Comment by marklcg** [comment]
Ok, have a fix.  The latest destroyEditor was stealing focus.  I refocus now.  I ran into recursion, so had to add a bit of a hack to prevent that.  Seems to work. See commit referenced above.
